### ISSUE TITLE
Nexus Question...

### ISSUE THREAD

**Issue by geopayme** [libreATM/hardware_manuals#1]
I had two questions

Why use only a Nexus Tablet?

and Why Tethering is needed? Maybe it needs a bit more clarity

**Comment by kresp0** [comment]
> Why use only a Nexus Tablet?

I think that any tablet should work.
The Nexus was(is?) the tablet used on the original skyhook ATM and the only one I have to play with.

> and Why Tethering is needed? Maybe it needs a bit more clarity

Because the browser on the tablet has to access the website on the raspberry pi. See:
https://github.com/libreATM/docs/blob/master/How_to_Install_libreATM_on_a_Skyhook_from_scratch.md

I think that would be great to remove the raspberry and have the webserver running on the tablet itself. Then a tablet with OTG support would be needed (the nexus has) to connect it to the bill validator.
